# Generated by Django 3.1.2 on 2020-10-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApi', '0002_auto_20201025_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='post_instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='color',
            name='post_twitter_link',
            field=models.URLField(blank=True),
        ),
    ]
