# Generated by Django 3.1.2 on 2020-10-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApi', '0003_auto_20201028_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='post_twitter_link',
        ),
    ]
