# Generated by Django 3.1.2 on 2020-10-25 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors_artist_name', models.CharField(max_length=100)),
                ('colors_song_title', models.CharField(max_length=100)),
                ('colors_artist_photo', models.URLField()),
                ('colors_cover_photo', models.URLField()),
                ('colors_video', models.URLField()),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mobile', models.CharField(max_length=10)),
                ('user_street_address_1', models.CharField(max_length=150)),
                ('user_street_address_2', models.CharField(blank=True, max_length=150)),
                ('user_city', models.CharField(max_length=150)),
                ('user_province', models.CharField(max_length=150)),
                ('user_country', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_order_id', models.CharField(max_length=150)),
                ('order_song', models.CharField(max_length=150)),
                ('order_item', models.CharField(max_length=150)),
                ('order_date', models.DateField()),
                ('order_price', models.CharField(max_length=150)),
                ('order_placed', models.BooleanField()),
                ('order_on_its_way', models.BooleanField()),
                ('order_completed', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_title', models.CharField(max_length=50)),
                ('notification_message', models.CharField(max_length=150)),
                ('notification_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
