# Generated by Django 3.1.2 on 2020-10-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colors',
            new_name='Color',
        ),
    ]
